#!/usr/bin/env python3
"""Generate camfr/math/calculus/quadrature/patterson_coeff.cpp from MATH77.

The coefficients of the Patterson quadrature formulas, in the representation
of Krogh and Snyder, are taken from the DATA statements for P in dinta.f of
the JPL MATH77 library (Copyright 1996 Caltech, BSD licence), available from
netlib:

    curl -O https://www.netlib.org/math/math77.tgz
    tar xzf math77.tgz MATH77/dinta.f MATH77/license
    python3 tools/patterson/coefficients_from_math77.py MATH77/dinta.f \
        > camfr/math/calculus/quadrature/patterson_coeff.cpp

The values are copied digit for digit (Fortran D exponents become e).
"""

import re
import sys

LICENSE = """\
// Copyright (c) 1996 California Institute of Technology, Pasadena,
// California.  ALL RIGHTS RESERVED.  Based on Government Sponsored
// Research NAS7-03001.  Redistribution and use in source and binary
// forms, with or without modification, are permitted provided that the
// following conditions are met: Redistributions of source code must
// retain this copyright notice, this list of conditions and the
// following disclaimer.  Redistributions in binary form must reproduce
// the above copyright notice, this list of conditions and the following
// disclaimer in the documentation and/or other materials provided with
// the distribution.  Neither the name of the California Institute of
// Technology (Caltech) nor the names of its contributors may be used to
// endorse or promote products derived from this software without
// specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE
// COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
// BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
// OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
// IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."""

HEADER = """\
/////////////////////////////////////////////////////////////////////////////
//
// File:     patterson_coeff.cpp
//
// Coefficients of the Patterson quadrature formulas (T. N. L. Patterson,
// Math. Comp. 22, 847-856, 1968) in the representation of F. T. Krogh and
// W. V. Snyder: for each formula, the corrections to the stored function
// values of the previous formulas, then (1 - |node|, weight) pairs for the
// new nodes. See patterson_rule.h.
//
// GENERATED by tools/patterson/coefficients_from_math77.py from the DATA
// statements for P in dinta.f of the JPL MATH77 library, under the
// following licence (MATH77/license, netlib.org/math):
//
{license}
//
/////////////////////////////////////////////////////////////////////////////

#include "patterson_rule.h"

const Real patterson_p[{size}] = {{
  0.0, // Unused: the table is indexed from 1, as in MATH77.
{values}
}};
"""


def main(path):
    text = open(path).read()
    data = {int(i): v for i, v in
            re.findall(r"DATA P\(\s*(\d+)\)\s*/\s*([+-]?\.\d+D[+-]\d+)\s*/",
                       text)}
    n = max(data)
    missing = [i for i in range(1, n + 1) if i not in data]
    if missing:
        sys.exit(f"missing coefficients: {missing}")
    values = "\n".join(f"  {data[i].replace('D', 'e')}, // {i}"
                       for i in range(1, n + 1))
    sys.stdout.write(HEADER.format(license=LICENSE, size=n + 1,
                                   values=values))


if __name__ == "__main__":
    main(sys.argv[1])
